import type { CartItem, OrderPreview, ProductSummary } from '../../types';
import { formatPrice, isSoldOut } from '../../lib/utils';
import { Badge, Button, Card, EmptyState, SectionHeading, SkeletonBlock } from '../ui';

export function CartSection({ cart, productsById, preview, loading, onMoveToCatalog, onUpdateQuantity, onSubmitOrder }: { cart: CartItem[]; productsById: Map<number, ProductSummary>; preview: OrderPreview | null; loading: boolean; onMoveToCatalog: () => void; onUpdateQuantity: (item: CartItem, quantity: number) => void; onSubmitOrder: () => void }) {
  return <Card id="cart" className="border-slate-900/90 bg-slate-950 text-white shadow-[0_25px_80px_rgba(15,23,42,0.2)]"><div className="flex items-end justify-between gap-4"><SectionHeading eyebrow="Cart" title="현재 담긴 상품" description="상품 옵션과 결제 예상 금액을 빠르게 스캔할 수 있도록 명도 대비를 높인 요약 패널입니다." invert /><Badge variant="secondary-dark">{cart.length} items</Badge></div><div className="mt-6 space-y-3">{loading ? Array.from({ length: 3 }).map((_, index) => <div key={`cart-skeleton-${index}`} className="rounded-2xl border border-white/10 bg-white/5 p-4"><SkeletonBlock className="h-4 w-2/3 bg-white/10" /><SkeletonBlock className="mt-3 h-3 w-1/3 bg-white/10" /><SkeletonBlock className="mt-4 h-3 w-full bg-white/10" /></div>) : cart.length === 0 ? <EmptyState title="장바구니가 비었습니다" description="원하는 상품을 둘러보고 다시 담아 보세요. 담는 즉시 이 요약 패널에 반영됩니다." actionLabel="쇼핑 계속하기" onAction={onMoveToCatalog} tone="inverted" /> : cart.map((item) => <CartItemCard key={item.cartItemId} item={item} product={productsById.get(item.productId)} onUpdateQuantity={onUpdateQuantity} />)}</div><div className="mt-6 rounded-[24px] border border-white/10 bg-white/8 p-4"><div className="flex items-center justify-between text-sm text-slate-300"><span>상품 합계</span><span>{formatPrice(preview?.subtotal ?? 0)}</span></div><div className="mt-2 flex items-center justify-between text-sm text-slate-300"><span>배송비</span><span>{formatPrice(preview?.shippingFee ?? 0)}</span></div><div className="mt-3 flex items-center justify-between border-t border-white/10 pt-3 text-base font-semibold text-white"><span>예상 결제</span><span>{formatPrice(preview?.totalAmount ?? 0)}</span></div><Button className="mt-4 w-full" size="lg" variant="light" onClick={onSubmitOrder}>주문 완료 시뮬레이션</Button></div></Card>;
}

function CartItemCard({ item, product, onUpdateQuantity }: { item: CartItem; product?: ProductSummary; onUpdateQuantity: (item: CartItem, quantity: number) => void }) {
  const soldOut = product ? isSoldOut(product) : false;
  return <div className="rounded-[22px] border border-white/10 bg-white/6 p-4 transition-colors duration-200 hover:bg-white/8"><div className="flex items-start justify-between gap-3"><div className="space-y-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-medium text-white">{item.productName}</p>{soldOut ? <Badge variant="secondary-dark">품절</Badge> : null}</div><p className="text-xs text-slate-400">{item.optionLabel}</p></div><p className="text-sm font-semibold text-white">{formatPrice(item.lineTotal)}</p></div><div className="mt-4 flex items-center justify-between gap-4 text-xs text-slate-400"><div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-slate-950/40 px-2 py-1"><Button size="sm" variant="ghost" className="h-8 w-8 rounded-full px-0 text-white hover:bg-white/10 hover:text-white" onClick={() => onUpdateQuantity(item, item.quantity - 1)} ariaLabel={`${item.productName} 수량 감소`}>−</Button><span className="min-w-8 text-center text-sm font-semibold text-white">{item.quantity}</span><Button size="sm" variant="ghost" className="h-8 w-8 rounded-full px-0 text-white hover:bg-white/10 hover:text-white" onClick={() => onUpdateQuantity(item, item.quantity + 1)} ariaLabel={`${item.productName} 수량 증가`}>+</Button></div><span>{formatPrice(item.unitPrice)} / 개</span></div></div>;
}
